### PR TITLE
Fix #44: update ace to 1.2.2

### LINKED ISSUE #44: Update ace to 1.2.2
It'd be great to update ace to the latest version (`1.2.2`).

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR is just a bump of the ace version with `npm run update`.

### CODE REVIEW

**Comment by thlorenz** [comment]
Awesome, added you as a collab.
Please run `npm test` and check that all editors contain error annotations.
Then feel free to merge to master [following this](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84#merging-a-pr) and ping me, so I can version and publish.

**Comment by JackuB** [comment]
> Please run npm test and

Why not run it in CI?

**Comment by thlorenz** [comment]
It's a visual test ;)

**Comment by elijahsmith** [comment]
I just ran {{npm test}} in @SamyPesse's repo and the resulting page looks identical to that from this repo.

**Comment by globetro** [comment]
Any ETA on when this PR will get merged?

**Comment by thlorenz** [comment]
Waiting for @SamyPesse to merge it so I can publish new version.

**Comment by elijahsmith** [comment]
bump, we're waiting on this as well... is it critical that @SamyPesse do the merge?  can't you @thlorenz merge it yourself?

**Comment by elijahsmith** [comment]
@thlorenz if I were to recreate this PR from my own fork, would you be open to merging it or allowing me to?

**Comment by thlorenz** [comment]
@elijahsmith added you as collab, please merge this PR so I can publish new version.

**Comment by elijahsmith** [comment]
thank you, done.  How would you feel about putting out a 0.5.3 release?

**Comment by thlorenz** [comment]
Thanks, published as `0.6`.

**Pull request merged**
