### PR TITLE
Add type definitions for use in TypeScript

### PR DESCRIPTION
**Pull request by tbekolay**
Hello! Thanks for `brace`, it's been very useful in our application, which we build with webpack.

We've recently ported over our codebase from raw JS to TypeScript, and found that the [available type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ace/ace.d.ts) don't work with brace out of the box. This commit adds definitions that work, generated by a similar process as brace uses to generate JS source (see the commit message for more details).

I chose to do this with a separate `update-ts.js` script exposed through an npm `update-ts` command, but if you prefer I could instead add the contents of `update-ts.js` to the existing `update.js`.

Alternatively, if you'd prefer that type definitions live outside of this repository, I'm happy to make a separate repository for this. However, I'm submitting this PR first as it's nice to be able to `npm install brace` and have the type definitions automatically available without the extra step of downloading them with `typings`.

### CODE REVIEW

**Comment by thlorenz** [comment]
Nice! this looks good to me except for two things:

- we should update the ts definitions when doing `npm run update` as I can't see a reason why you'd update the code but not the typescript definitions
- explain something in the Readme about the typescript definitions so people understand what they are, why they are there and how to use them

Thanks for your work! (not a typescript user myself, but I bet this will help lots of others that are)

**Comment by tbekolay** [comment]
Sounds good! I'll update this PR tomorrow to include those two things.

**Comment by thlorenz** [comment]
@tbekolay made you collaborator.

So once you make those changes an I reviewed them, please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by tbekolay** [comment]
I made these changes in a fixup commit (ada4a6f04c0f34) so you can see the diff. Before fast-forward merging, I will squash these two commits into one commit (we also avoid merge commits in our project, so these steps are familiar to me).

**Comment by thlorenz** [comment]
LGTM, please merge to master.
I'll pub a new version.

And sorry for the long delay

**Comment by thlorenz** [comment]
BTW one thing I'm not a huge fan of is the code duplication in the update scripts.
I.e. when we fix a bug in one ppl who don't care about typescript (that'd be me as well) will fail to fix it there as well.
Ideally we'd pull some of this out into reusable functions which both updaters pull in and use.

**Comment by tbekolay** [comment]
> I'm not a huge fan of is the code duplication in the update scripts.

Yes, I agree this is not ideal. I'll merge for now, but I'll add reducing duplication to my todo list.

**Comment by thlorenz** [comment]
Thanks published as 0.9

**Pull request merged**
