### PR TITLE
Snippets support

### LINKED ISSUE #56: snippets are missing
When creating a javascript editor with enableSnippets enabled, ace tries to load snippets/javascript.js from the server but it doesn't exist so an exception is raised.
Adding brace/snippets folder from the ace repository, and requiring this file in the code, solves this problem.
Am I missing something? or the snippets should be entered to brace?

### PR DESCRIPTION
**Pull request by gokmen**
- Adds snippets into root, updater updated (fixes #56) 
- `ace.d.ts` renamed as `index.d.ts` on https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/ace 
  It was failing to update TypeScript version, includes a fix for that one as well.

### CODE REVIEW

**Comment by gokmen** [comment]
ping @thlorenz

**Comment by gokmen** [comment]
ping @thlorenz

**Comment by thlorenz** [comment]
Ah sorry @gokmen this slipped me by. The PR LGTM.

Made you collaborator.

Please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by gokmen** [comment]
@thlorenz just rebased & merged 👍

**Comment by thlorenz** [comment]
Thanks, went out as `0.10`

**Pull request merged**
