### PR TITLE
Update Ace v1.2.5

### PR DESCRIPTION
**Pull request by ceritium**

### CODE REVIEW

**Comment by thlorenz** [comment]
Hey sorry for not getting to this sooner.
Is this still the latest version, i.e. would it fix #72 ?

**Comment by ceritium** [comment]
Probably #72 is fixed, check it https://github.com/ajaxorg/ace/pull/3116

**Comment by ja0n** [comment]
> Is this still the latest version, i.e. would it fix #72 ?

[ajaxorg/ace#3116](https://github.com/ajaxorg/ace/pull/3116) is shipping on [v1.2.6](https://github.com/ajaxorg/ace/releases/tag/v1.2.6) that was released 1 day ago
see [the commit](https://github.com/ajaxorg/ace/commit/98a31b381b1a6b0012fd34bdcb86c05f39df6253)

**Comment by thlorenz** [comment]
Superseded by #73

**Pull request closed without merging**
