### PR TITLE
Include HTML worker in update script

### PR DESCRIPTION
**Pull request by jedfoster**
Addresses #24.

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM in general so after you fix the nit we can pull this in.

**Comment by thlorenz** [comment]
Made you collab, so you can pull this and the other PR in.

Please don't change version of in `package.json` though. I'll update that myself and will publish.
This should be a minor upgrade I suppose?

**Comment by thlorenz** [comment]
BTW squash these two commits before merging of course ;)

**Comment by jedfoster** [comment]
Closed with 3d8ffb8

**Pull request closed without merging**
