### PR TITLE
update ACE to 1.1.9

### PR DESCRIPTION
**Pull request by mstorus**
updated `var aceTag = 'v1.1.9';` and then ran `npm run update`

### CODE REVIEW

**Comment by thlorenz** [comment]
Please remove last commit as it doesn't do anything useful.

**Comment by mstorus** [comment]
sorry please hold on, I think someone has stolen my email address
the commits are coming from the wrong person. Contacting GitHub to sort it out...

**Comment by mstorus** [comment]
updated

**Comment by thlorenz** [comment]
Thanks, went out with 0.5.1.

**Pull request closed without merging**
