### PR TITLE
Xml worker

### PR DESCRIPTION
**Pull request by bryce-gibson**
This PR adds xml to the worker config so that the xml_worker is created.

Prior to this, in my environment, the xml_worker failed to load and hence no annotations were shown.

With this change and a rebuild the annotations seem to work as expected.

This PR also adds the xml worker to the svg and markdown builds as well as the xml one; as it _seemed_ correct (as they both reference the xml worker) -- but this may be the wrong thing to do (I may not correctly understand what's going on :-) ) -- Not really sure if it's actually doing anything; it just seemed like the right thing to do...

I wasn't sure whether you'd want the rebuilt output as PR :-s
Happy to provide if helpful.

### CODE REVIEW

**Comment by thlorenz** [comment]
Is this working for you. I remember I had difficulty with xml worker in the past.
If it is fine, please rerun the build script and add the changes to the PR.

Thanks.

**Comment by thlorenz** [comment]
Any update, otherwise I'll close this soon.

**Comment by bryce-gibson** [comment]
Sorry for that delay.

Just rechecked; seems to be working :-)

**Comment by thlorenz** [comment]
OK, in that case could you please include an XML example in the [tests](https://github.com/thlorenz/brace/blob/master/test/error-annotations.js)?
Just add another editor for XML, put some sample xml into it that has a mistake and ensure that error annotations are showing.

Thanks.

**Comment by thlorenz** [comment]
Shoot didn't see this for a long time, sorry.
Could you pls rebase on master (right now there are merge conflicts)? I promise this time I'll have a look much sooner :)

**Comment by bryce-gibson** [comment]
Rebased :-)

**Comment by thlorenz** [comment]
Awesome [merged](d56dc2d68e20a539b8a837585cb549dae5e5d7b2) and published as `0.7`.
Thanks a lot!

**Comment by bryce-gibson** [comment]
Absolutely no problem :-)

Thanks for brace :-)

**Pull request closed without merging**
