### PR TITLE
Fix typo: toggel -> toggle

### LINKED ISSUE #175: Typo in searchbox.js
'Toggel Replace Mode' instead of 'Toggle Replace Mode'

### PR DESCRIPTION
**Pull request by ogajduse**
Fixes #175

### CODE REVIEW

**Comment by thlorenz** [comment]
Please fix in the ace editor itself, this is just a fork that makes it bundleable.

**Comment by ogajduse** [comment]
> Please fix in the ace editor itself, this is just a fork that makes it bundleable.

It seems to be fixed in the ace editor already. Am I looking at the right location?
https://github.com/ajaxorg/ace/pull/3437/files#diff-b99eea4f7a1f541de20e5a632387e7c5497b475b25e3f037fec33181107fd9f3L59

**Comment by thlorenz** [comment]
Sure it's here: https://github.com/ajaxorg/ace

**Comment by ogajduse** [comment]
I am closing the issue due to lacking activity from the repository owner side.

**Pull request closed without merging**
