### PR TITLE
Brace 0.11.2 (bumps ace to 1.4.2; adds travis support)

### PR DESCRIPTION
**Pull request by StoneCypher**
This PR:

1. Bumps the underlying ACE implementation
1. Adds support for [Travis-CI](https://travis-ci.org/StoneCypher/brace/builds/473167811) assuming to check Node 8-11

### CODE REVIEW

**Comment by StoneCypher** [comment]
I pinged him on Twitter and he said he'd see to this mid-January

So I think this might be coming soon?

**Comment by StoneCypher** [comment]
@thlorenz Hey buddy, could you please hit merge?

**Comment by thlorenz** [comment]
I mean please don't change the brace version inside the package.json as I take care of that during the publish step to npm.

**Comment by StoneCypher** [comment]
I have removed the `.travis.yml` and regressed the version in `package.json`.

I believe that's what I'm supposed to do, but I have a bad flu and I'm stupid when I'm sick

**Comment by StoneCypher** [comment]
I will reintegrate travis in a followup PR if you say this is what you meant

**Comment by thlorenz** [comment]
OK, could you please squash all this into one commit?
Basically all we need for this PR are the changes in [this commit](https://github.com/thlorenz/brace/pull/152/commits/50d6e5b39fec05e172e441ef0a674276e4a43a15).

At this point there are tons of commits here including a merge of another PR which I'm not sure about why it is even here.
Alternatively open a new PR with just the upgrade related commit and we'll go from there.
Thanks.

**Comment by StoneCypher** [comment]
Oh.  Okay

**Comment by StoneCypher** [comment]
ahaaaa haaaaaaaaaaaa downloading large repos on conference wifi

**Comment by StoneCypher** [comment]
https://github.com/thlorenz/brace/pull/153

**Pull request closed without merging**
