### PR TITLE
Fix changeFold remove event bug

### PR DESCRIPTION
**Pull request by tylerstalder**
Fixed in upstream ace, but would be nice to have the fix in brace so that we don't need our own fork.

https://github.com/ajaxorg/ace/pull/2738

### CODE REVIEW

**Comment by thlorenz** [comment]
I prefer not to edit generated brace code.
Let's wait til ace releases a new version with your fix and tags it and then we can use [this script](https://github.com/thlorenz/brace/blob/master/build/update.js) in order to update to that version.

**Comment by tylerstalder** [comment]
Totally reasonable, thanks for looking.

**Comment by tylerstalder** [comment]
Bug made it into Ace, can we cut a new brace version?

https://github.com/ajaxorg/ace/blob/master/ChangeLog.txt

**Comment by thlorenz** [comment]
Of course! .. go ahead and [follow these instructions](https://github.com/thlorenz/brace#how-does-it-work) and submit a PR. Please make sure all tests pass as well. Thanks.

**Pull request closed without merging**
