### PR TITLE
Update ACE to 1.2.3

### PR DESCRIPTION
**Pull request by tylerstalder**
updated `var aceTag = 'v1.2.3';` and then ran `npm run update`

confirmed tests pass with `npm test`

### CODE REVIEW

**Comment by tylerstalder** [comment]
Any concerns getting this merged?

**Comment by afang** [comment]
Paging @thlorenz the PR seems to work.

**Comment by thlorenz** [comment]
@tylerstalder made you collaborator.

Please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by tylerstalder** [comment]
@thlorenz Thanks for adding me as a collaborator. Merged and pushed, please publish.

**Comment by thlorenz** [comment]
thanks published 0.8

**Pull request merged**
