### PR TITLE
Add keybindings to update script

### PR DESCRIPTION
**Pull request by jedfoster**
This addresses #21. I've confirmed the Vim keybindings work; the Emacs bindings should also work. #hjklForLife

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM, please **forward** merge into master (rebase as needed).

**Comment by thlorenz** [comment]
Awesome!
Could you add an example that uses vim bindings either to the wiki or in the `examples` folder?
I'd be ok with adding them to all the current examples there since vim is the right way to edit anyways ;)

**Comment by jedfoster** [comment]
I added Vim to the CoffeeScript and JavaScript examples.

**Comment by thlorenz** [comment]
Thanks, published as 0.5.

**Pull request merged**
